version: "3.8"

services:
  jenkins_service:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home

  liquibase_service:
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    container_name: liquibase
    volumes:
      - ./liquibase_changelog:/liquibase/changelog
    env_file: ./variables.env    
     